site_name: Tien Cao-hoang
pages:
- Home: index.md
- About: about.md
- HARDWARE:
  - Rasberry Pi: raspberry.md

- INTERNET OF THINGS:
  - Sitewhere: sitewhere.md
  
- LẬP TRÌNH WEB:
  - Lập trình web với Jekyll: jekyll.md

- Agrinode project: 
  - Devices list: agrinode_devices_list.md

- Links: links.md

theme: readthedocs
