site_name: Tien Cao-hoang
pages:
- Home: index.md
- About: about.md
- HARDWARE:
  - Rasberry Pi: hardware/raspberry.md

- INTERNET OF THINGS:
  - Sitewhere: IoT/sitewhere.md
  
- LẬP TRÌNH WEB:
  - Lập trình web với Jekyll: web/jekyll.md

- Agrinode project: 
  - Devices list: agrinode_devices_list.md

- Links: links.md

theme: readthedocs

copyright: Copyright &copy; 2016 <a href="http://chtien.xyz"> Tien Cao-hoang (http://chtien.xyz)</a>
